city = ("london")
print(city)
name = ("messi")
print(name)
sport = ("football")
print(city=name+age)
hobi(2gaming)
hobi = ("dance")
age(16wlis)
age = (16)
music = (2quens)
music = ("quens")           
movie = (2incredible)
movie = ("incredible")
tv_serial = (3prison_break)      
tv_serial = ("prison_break")
actor = (1johny_depp)
actor = ("johnu_depp")
actor = (1johny_depp)
actor = (1johny_depp)
actor = (1johny_depp)
actor = (1johny_depp)
tv_serial = (3prison_break)  
tv_serial = (3prison_break)  
tv_serial = (3prison_break)  
tv_serial = (3prison_break)  
music = ("quens")          
music = ("quens")          
music = ("quens")          
music = ("quens")          
tv_serial = ("prison_break")
tv_serial = ("prison_break")
tv_serial = ("prison_break")
tv_serial = ("prison_break")
hobi(2gaming)
hobi(2gaming)
hobi(2gaming)
hobi(2gaming)
age(16wlis)
age(16wlis)
name = ("messi")
name = ("messi")
name = ("messi")
name = ("messi")
sport = ("football")
sport = ("football")
sport = ("football")
sport = ("football")
hobi = ("dance")
hobi = ("dance")